import * as THREE from "three";

const racePerformance = {
    acceleration: 0.0015,
    accelerationCurveExponent: 1.45,
    collisionSlowScale: 0.62,
    deceleration: 0.00055,
    defaultGravity: new THREE.Vector3(0, -0.01, 0),
    draftAccelerationBonus: 0.34,
    draftChargeDecayPerMs: 0.00055,
    draftChargeGainPerMs: 0.0005,
    draftMaxSpeedBonus: 0.14,
    friction: 0.98,
    highSpeedTurnDamping: 0.22,
    lowSpeedAccelerationScale: 1.144,
    maxRoll: 0.36,
    maxSpeed: 0.99,
    minAccelerationScale: 0.28,
    turnInitialBoost: 1.192,
    turnRate: 0.0007752,
    turnSustainMs: 700,
    turnSustainScale: 0.84,
};

const raceNpc = {
    aggressionMax: 1.02,
    aggressionMin: 0.99,
    blockAwarenessDistance: 12,
    blockChance: 0.4,
    blockOffset: 1.6,
    cornerBrakeAssistFull: 0.82,
    cornerBrakeAssistMax: 0.28,
    cornerBrakeAssistRecoveryBonus: 0.12,
    cornerBrakeAssistStart: 0.34,
    cornerConfidenceMax: 1.06,
    cornerConfidenceMin: 1.03,
    cornerLineApexOffset: 0.92,
    cornerLineEntryOffset: 0.58,
    cornerLineExitOffset: 0.44,
    cornerLineOverspeedFadeScale: 0.65,
    cornerLineRecoveryScale: 0.16,
    cornerLineRiskFadeFull: 0.72,
    cornerLineRiskFadeStart: 0.32,
    cornerMinSpeedScale: 0.5,
    cornerPlannerBrakeGain: 0.7,
    cornerPlannerCatchupGain: 3.8,
    cornerPlannerFutureLift: 0.18,
    cornerPlannerHeavyThrottleFloor: 0.02,
    cornerPlannerLightThrottleFloor: 0.24,
    cornerPlannerOverspeedThrottleCut: 0.92,
    cornerPlannerPreBrakeFull: 0.74,
    cornerPlannerPreBrakeGain: 0.34,
    cornerPlannerPreBrakeStart: 0.28,
    cornerPlannerRiskThrottleFade: 0.82,
    corneringBiasMaxOffset: 1.18,
    cornerLoadFutureWeight: 0.08,
    cornerLoadImmediateWeight: 0.4,
    cornerLoadLaneWeight: 0.1,
    cornerLoadOverspeedWeight: 0.24,
    cornerLoadSaturationWeight: 0.08,
    cornerLoadSteerWeight: 0.1,
    cornerSteerAssistFull: 0.78,
    cornerSteerAssistMax: 0.24,
    cornerSteerAssistRecoveryBonus: 0.08,
    cornerSteerAssistStart: 0.3,
    draftPreferenceMax: 1.02,
    draftPreferenceMin: 1.0,
    draftSeekRadius: 8,
    draftSeekWeight: 1.0,
    forwardTargetDistance: 24,
    futureAwarenessDirectionWeight: 0.72,
    futureAwarenessFeedforwardWeight: 0.24,
    futureAwarenessSpeedBuffer: 0.08,
    futureAwarenessSteerWeight: 0.28,
    immediateCornerDirectionWeight: 0.68,
    immediateCornerSteerWeight: 0.32,
    intentMaxDurationMs: 1400,
    intentMinDurationMs: 700,
    laneChangeSmoothing: 0.11,
    maxLaneOffset: 2.6,
    farLookAheadMax: 96,
    farLookAheadMin: 38,
    midLookAheadMax: 42,
    midLookAheadMin: 20,
    minClosingSpeed: 0.05,
    nearLookAheadMax: 18,
    nearLookAheadMin: 7.5,
    oversteerRetreatScale: 0.45,
    overtakeLaneOffset: 1.95,
    overtakeTriggerDistance: 7.5,
    pathSearchFallbackDistanceSq: 196,
    previewFarDirectionWindow: 18,
    previewMidDirectionWindow: 9.5,
    previewNearDirectionWindow: 4.5,
    rearBumpChance: 0.2,
    rearCorridorWidth: 1.9,
    recoveryErrorThreshold: 0.38,
    recoveryImmediateRiskThreshold: 0.52,
    recoveryLaneOffsetScale: 0.42,
    recoveryOverspeedThreshold: 0.08,
    recoverySteerThreshold: 0.68,
    sideBySideLength: 5.6,
    sidePressureChance: 0.3,
    sidePressureOffset: 1.05,
    sidePressureRange: 4.2,
    sidePressureRelativeSpeed: 0.22,
    skillMax: 1.02,
    skillMin: 1.0,
    startBoostDurationMs: 2000,
    startDraftLaneScale: 0.18,
    startBoostScale: 1.9,
    startTacticalSuppressionMs: 2000,
    steerErrorForFullInput: 0.58,
    steerRecoveryMax: 1.06,
    steerRecoveryMin: 1.03,
    steerFarWeight: 0.12,
    steerFeedforwardClamp: 0.42,
    steerFeedforwardWeight: 0.52,
    steerMidWeight: 0.24,
    steerNearWeight: 0.7,
    steeringSmoothingBase: 0.22,
    tacticalCornerLoadFadeFull: 0.44,
    tacticalCornerLoadFadeStart: 0.14,
    tacticalCorneringSuppressionStart: 0.24,
    tacticalCorneringSuppressionFull: 0.5,
    understeerBrakeScale: 0.1,
    understeerErrorThreshold: 0.42,
    understeerSpeedRatio: 0.7,
    understeerThrottleScale: 0.62,
    dynamicLaneOffsetBlend: 0.2,
    recoveryLaneOffsetBlend: 0.34,
    dynamicPlanner: {
        attackBiasScale: 0.22,
        attackOffset: 0.82,
        beamWidth: 7,
        brakingLookAheadSamples: 9,
        brakingReserveFactor: 1.55,
        blockBiasScale: 0.2,
        blockLookAheadDistance: 20,
        collisionPenalty: 4.1,
        collisionPredictionLength: 10.5,
        controlPenalty: 0.84,
        cornerBrakeScale: 0.54,
        cornerCorridorShrink: 0.58,
        cornerEntryOffsetScale: 0.42,
        cornerExitOffsetScale: 0.34,
        cornerRiskFadeFull: 0.82,
        cornerRiskFadeStart: 0.28,
        corridorPenalty: 1.92,
        draftBiasScale: 0.22,
        draftLookAheadDistance: 16,
        emergencyBrakeScale: 1.36,
        emergencySteerDamping: 0.74,
        fallbackBrake: 0.18,
        fallbackThrottle: 0.5,
        guardianBrakeFloor: 0.34,
        guardianCorridorThreshold: 0.62,
        guardianLookAheadDistance: 58,
        guardianOverspeedThreshold: 0.09,
        heavyCornerSpeedFloor: 0.2,
        hardCorridorMargin: 0.76,
        horizonDistanceBase: 38,
        horizonDistanceMax: 160,
        horizonDistanceSpeedScale: 64,
        laneCandidates: [-0.9, -0.6, -0.3, 0, 0.3, 0.6, 0.9],
        linkedCornerLookAhead: 120,
        maxBrakePerMeter: 0.038,
        maxLateralAcceleration: 0.112,
        maxLaneUsage: 0.88,
        maxOverspeedForViablePlan: 0.08,
        mediumCornerSpeedFloor: 0.28,
        minCollisionDistance: 2.8,
        minRollingSpeed: 0.22,
        minSegmentDistance: 3.5,
        overtakeBiasScale: 0.25,
        overtakeLookAheadDistance: 14,
        plannerAccelerationScale: 0.024,
        plannerMaxSpeedSafety: 0.95,
        previewExecutionDistance: 26,
        recoveryCenteringGain: 0.68,
        recoveryDistanceLimit: 0.78,
        recoveryThrottleCap: 0.38,
        safetyMargin: 0.9,
        segmentCount: 8,
        segmentDistanceMin: 5.5,
        segmentDistanceSpeedScale: 5.5,
        sideAttackChance: 0.28,
        speedBrakeGain: 4.9,
        speedLookAheadBlend: 0.66,
        speedThrottleGain: 2.2,
        steeringGain: 0.56,
        targetSpeedLookAheadIndex: 3,
        trackProgressRewardScale: 0.11,
        trackSafetyBias: 1.26,
        transitionPenalty: 0.52,
        viabilityControlDemandLimit: 0.74,
        viabilityPredictionWindow: 68,
    },
};

const raceCamera = {
    draftFovBonus: 8,
    highSpeedFov: 94,
    lowSpeedFov: 64,
    maxFov: 100,
    smoothing: 0.08,
};

const raceTrail = {
    centerFadeRadiusPx: 240,
    clusterOpacity: 0.3,
    clusterScale: 1.04,
    clusterSpread: 0.82,
    draftBehindDistance: 3.6,
    draftHeadExclusionDistance: 4.8,
    draftProbeForwardOffset: 0.85,
    draftZoneRadius: 2.6,
    draftTrailResetDistance: 18,
    fadeEndDistance: 5.5,
    fadeStartDistance: 11,
    flowSpeed: 0.006,
    haloOpacity: 0.16,
    haloScale: 1.86,
    markerCountdownFadeScale: 0.18,
    markerFontMinPx: 11,
    markerFontScaleVw: 0.9,
    markerFontSizePx: 16,
    markerPointerHeightPx: 8,
    markerPointerWidthPx: 4,
    markerWorldOffset: 1.35,
    maxLength: 58,
    maxMarkerOpacity: 1,
    minDisplayLength: 2.4,
    minDisplaySpeed: 0.08,
    minLength: 12,
    minMarkerOpacity: 0,
    opacity: 0.42,
    particleOpacity: 0,
    particleScale: 0.48,
    particleSpread: 0.52,
    sampleCount: 72,
    lengthExponent: 1.9,
    wobbleStrength: 0,
};

const raceCollision = {
    frontBackReboundBase: 0.16,
    frontBackReboundFrontScale: 1.15,
    frontBackReboundRearScale: 1.0,
    frontBackThreshold: 0.72,
    pushStrength: 0.16,
    sideImpactSlowFastScale: 0.82,
    sideImpactSlowSlowScale: 0.55,
    sideImpactSpeedBiasCap: 0.35,
    sideImpactSpeedBiasScale: 0.45,
    slowDurationMs: 450,
};

const raceIdentityColors = [
    0xffd166,
    0x06d6a0,
    0x4cc9f0,
    0xf72585,
    0xb8f35a,
    0xff8fab,
];

export {
    raceCamera,
    raceCollision,
    raceIdentityColors,
    raceNpc,
    racePerformance,
    raceTrail,
};
