import * as THREE from "three";

const racePerformance = {
    acceleration: 0.00125,
    accelerationCurveExponent: 1.45,
    collisionSlowScale: 0.62,
    deceleration: 0.00055,
    defaultGravity: new THREE.Vector3(0, -0.01, 0),
    draftAccelerationBonus: 0.5,
    draftChargeDecayPerMs: 0.00045,
    draftChargeGainPerMs: 0.0007,
    draftMaxSpeedBonus: 0.25,
    friction: 0.98,
    highSpeedTurnDamping: 0.22,
    lowSpeedAccelerationScale: 1.12,
    maxRoll: 0.36,
    maxSpeed: 0.9,
    minAccelerationScale: 0.28,
    turnInitialBoost: 1.16,
    turnRate: 0.00076,
    turnSustainMs: 700,
    turnSustainScale: 0.84,
};

const raceNpc = {
    aggressionMax: 1.1,
    aggressionMin: 0.9,
    blockAwarenessDistance: 12,
    blockChance: 0.4,
    blockOffset: 2.1,
    cornerConfidenceMax: 1.04,
    cornerConfidenceMin: 0.96,
    draftPreferenceMax: 1.08,
    draftPreferenceMin: 0.95,
    draftSeekRadius: 8,
    draftSeekWeight: 1.0,
    forwardTargetDistance: 24,
    intentMaxDurationMs: 1400,
    intentMinDurationMs: 700,
    laneChangeSmoothing: 0.075,
    maxLaneOffset: 3.2,
    maxLookAhead: 13,
    minClosingSpeed: 0.05,
    minLookAhead: 4.5,
    oversteerRetreatScale: 0.45,
    overtakeLaneOffset: 2.45,
    overtakeTriggerDistance: 7.5,
    pathSearchFallbackDistanceSq: 196,
    rearBumpChance: 0.2,
    rearCorridorWidth: 1.9,
    sideBySideLength: 5.6,
    sidePressureChance: 0.3,
    sidePressureOffset: 1.45,
    sidePressureRange: 4.2,
    sidePressureRelativeSpeed: 0.22,
    skillMax: 1.03,
    skillMin: 0.94,
    startBoostDurationMs: 2000,
    startDraftLaneScale: 0.18,
    startBoostScale: 1.75,
    startTacticalSuppressionMs: 2000,
    steerErrorForFullInput: 0.75,
    steerNoiseMax: 0.035,
    steerNoiseMin: 0.015,
    steerRecoveryMax: 1.06,
    steerRecoveryMin: 0.92,
    steeringNoiseSpeed: 0.0042,
    steeringSmoothingBase: 0.14,
    understeerBrakeScale: 0.22,
    understeerErrorThreshold: 0.42,
    understeerSpeedRatio: 0.64,
    understeerThrottleScale: 0.42,
};

const raceCamera = {
    draftFovBonus: 8,
    highSpeedFov: 94,
    lowSpeedFov: 64,
    maxFov: 100,
    smoothing: 0.08,
};

const raceTrail = {
    centerFadeRadiusPx: 240,
    clusterOpacity: 0.3,
    clusterScale: 1.04,
    clusterSpread: 0.82,
    draftZoneRadius: 2.6,
    fadeEndDistance: 5.5,
    fadeStartDistance: 11,
    flowSpeed: 0.006,
    haloOpacity: 0.16,
    haloScale: 1.86,
    markerCountdownFadeScale: 0.18,
    markerFontMinPx: 11,
    markerFontScaleVw: 0.9,
    markerFontSizePx: 16,
    markerPointerHeightPx: 8,
    markerPointerWidthPx: 4,
    markerWorldOffset: 1.35,
    maxLength: 58,
    maxMarkerOpacity: 1,
    minDisplayLength: 2.4,
    minDisplaySpeed: 0.08,
    minLength: 12,
    minMarkerOpacity: 0,
    opacity: 0.42,
    particleOpacity: 0,
    particleScale: 0.48,
    particleSpread: 0.52,
    sampleCount: 72,
    lengthExponent: 1.9,
    wobbleStrength: 0,
};

const raceCollision = {
    frontBackReboundBase: 0.16,
    frontBackReboundFrontScale: 1.15,
    frontBackReboundRearScale: 1.0,
    frontBackThreshold: 0.72,
    pushStrength: 0.16,
    sideImpactSlowFastScale: 0.82,
    sideImpactSlowSlowScale: 0.55,
    sideImpactSpeedBiasCap: 0.35,
    sideImpactSpeedBiasScale: 0.45,
    slowDurationMs: 450,
};

const raceIdentityColors = [
    0xffd166,
    0x06d6a0,
    0x4cc9f0,
    0xf72585,
    0xb8f35a,
    0xff8fab,
];

export {
    raceCamera,
    raceCollision,
    raceIdentityColors,
    raceNpc,
    racePerformance,
    raceTrail,
};
